# Generated by Django 5.0 on 2026-05-28 04:31

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='culture',
            options={'ordering': ['name'], 'verbose_name': 'Культура', 'verbose_name_plural': 'Культуры'},
        ),
        migrations.AlterModelOptions(
            name='gardenplot',
            options={'ordering': ['-created_at'], 'verbose_name': 'Участок', 'verbose_name_plural': 'Участки'},
        ),
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['-priority', '-created_at'], 'verbose_name': 'Рекомендация', 'verbose_name_plural': 'Рекомендации'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name'], 'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.AlterModelOptions(
            name='weatherrecord',
            options={'ordering': ['-date'], 'verbose_name': 'Запись погоды', 'verbose_name_plural': 'Записи погоды'},
        ),
        migrations.AddField(
            model_name='gardenplot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 5, 28, 9, 31, 30, 190611)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='culture',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='image',
            field=models.ImageField(blank=True, upload_to='cultures/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='max_planting_temp',
            field=models.FloatField(verbose_name='Макс. температура посадки'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='min_planting_temp',
            field=models.FloatField(verbose_name='Мин. температура посадки'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='vegetation_days',
            field=models.PositiveIntegerField(verbose_name='Дней вегетации'),
        ),
        migrations.AlterField(
            model_name='gardenplot',
            name='area',
            field=models.FloatField(verbose_name='Площадь, сот.'),
        ),
        migrations.AlterField(
            model_name='gardenplot',
            name='cultures',
            field=models.ManyToManyField(blank=True, related_name='plots', to='weather.culture'),
        ),
        migrations.AlterField(
            model_name='gardenplot',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название участка'),
        ),
        migrations.AlterField(
            model_name='gardenplot',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plots', to='weather.region'),
        ),
        migrations.AlterField(
            model_name='gardenplot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='weather.gardenplot'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Низкий'), (2, 'Средний'), (3, 'Высокий')], default=1, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='text',
            field=models.TextField(verbose_name='Рекомендация'),
        ),
        migrations.AlterField(
            model_name='region',
            name='climate_zone',
            field=models.CharField(choices=[('north', 'Северный'), ('central', 'Центральный'), ('south', 'Южный')], max_length=20, verbose_name='Климатическая зона'),
        ),
        migrations.AlterField(
            model_name='region',
            name='latitude',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='region',
            name='longitude',
            field=models.FloatField(verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='weatherrecord',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='weatherrecord',
            name='humidity',
            field=models.PositiveSmallIntegerField(verbose_name='Влажность, %'),
        ),
        migrations.AlterField(
            model_name='weatherrecord',
            name='precipitation',
            field=models.FloatField(default=0, verbose_name='Осадки, мм'),
        ),
        migrations.AlterField(
            model_name='weatherrecord',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_records', to='weather.region'),
        ),
        migrations.AlterField(
            model_name='weatherrecord',
            name='temp_max',
            field=models.FloatField(verbose_name='Макс. температура'),
        ),
        migrations.AlterField(
            model_name='weatherrecord',
            name='temp_min',
            field=models.FloatField(verbose_name='Мин. температура'),
        ),
        migrations.AlterUniqueTogether(
            name='weatherrecord',
            unique_together={('region', 'date')},
        ),
    ]
