# Generated by Django 5.0 on 2026-06-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_culture_options_alter_gardenplot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='soil_type',
            field=models.CharField(choices=[('chernozem', 'Чернозём'), ('loam', 'Суглинок'), ('sandy', 'Песчаная'), ('clay', 'Глинистая'), ('podzolic', 'Дерново-подзолистая')], default='loam', max_length=20, verbose_name='Тип почвы'),
        ),
    ]
