# Generated by Django 5.0 on 2026-06-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_planting'),
    ]

    operations = [
        migrations.AddField(
            model_name='gardenplot',
            name='soil_type',
            field=models.CharField(choices=[('chernozem', 'Чернозём'), ('loam', 'Суглинок'), ('sandy', 'Песчаная'), ('clay', 'Глинистая'), ('podzolic', 'Дерново-подзолистая')], default='loam', max_length=20, verbose_name='Тип почвы на участке'),
        ),
    ]
