# Generated by Django 5.0 on 2026-06-02 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_gardenplot_soil_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='planting_month_end',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Конец посадки (месяц)'),
        ),
        migrations.AddField(
            model_name='culture',
            name='planting_month_start',
            field=models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Начало посадки (месяц)'),
        ),
    ]
